### PR TITLE
Chris Denniston Final Project

### PR DESCRIPTION
**Pull request by octopuscabbage**
Contains code for both of my projects

### CODE REVIEW

**Comment by SachitNayak** [comment]
Bro you have conflicting files here! Please donot change the named_entity/ner.py because all of others' code are dependent on it!!

**Comment by ken-dall** [comment]
+1 from @SachitNayak . looks like this would delete the parent class [ner.py] file outright

**Comment by Lakshya-Kejriwal** [comment]
I am also using the original `ner.py` file. Since I am doing a relative import accepting this PR will cause my code to crash. Please update your PR.

**Comment by octopuscabbage** [comment]
I am in the middle of changing it

**Pull request closed without merging**
